export const products = [
	{
		id: 1,
		img: 'https://firebasestorage.googleapis.com/v0/b/portfolio-pauljeon.appspot.com/o/ecommerce-1.png?alt=media&token=5782cf9f-aacb-4c41-8326-adb9ab201dc9',
		link: 'https://pauljeonn-ecommerce.herokuapp.com/',
		title: 'E-Commerce App',
		team: '개인 프로젝트',
		desc: 'MERN Stack을 사용하여 온라인 쇼핑몰 웹사이트를 제작하였습니다. Redux를 통해 전역 상태관리를 하였고, styled-components를 통해 컴포넌트들을 동적으로 자유롭게 스타일링 할 수 있었습니다. 백엔드 동작원리에 대해 많이 이해하게 되었으며 Node.js에서 MongoDB와 연동하여 서버를 구축하고 사용하는 법을 배웠습니다. 풀스택으로 앱이 작동하는 모든 과정을 체험해볼 수 있었습니다.',
		tech: [
			'React',
			'Redux',
			'styled-components',
			'Node.js',
			'Express',
			'MongoDB',
			'Heroku',
		],
		front: 'React, Redux, styled-components',
		back: ' Node.js, Express, MongoDB',
		deploy: 'Heroku',
		github: 'https://github.com/pauljeonn/react-ecommerce',
	},
	{
		id: 2,
		img: 'https://firebasestorage.googleapis.com/v0/b/portfolio-pauljeon.appspot.com/o/covid-1.png?alt=media&token=13044dbd-e989-426d-b95d-26c629aa3c70',
		link: 'https://react-covid-app-cccc4.web.app/',
		title: 'COVID-19 App',
		team: '개인 프로젝트',
		desc: '매일 업데이트되는 코로나 세계 각국 현황을 API 연동을 통해 한 눈에 차트로 비교해 볼 수 있는 웹사이트입니다. 타입스크립트 기반으로 진행하였으며 Emotion을 사용하여 styled-components 문법으로 스타일링 하였습니다. Chart.js 라이브러리를 통해 Bar Chart를 생성하여 데이터를 시각화 하였습니다.',
		tech: ['TypeScript', 'React', 'Emotion', 'Chart.js', 'Firebase'],
		front: 'React(TypeScript), Emotion, Chart.js',
		deploy: 'Firebase',
		github: 'https://github.com/pauljeonn/react-covid-app',
	},
	// {
	// 	id: 2,
	// 	img: 'https://firebasestorage.googleapis.com/v0/b/portfolio-pauljeon.appspot.com/o/nike.png?alt=media&token=13f2587a-202d-4307-b2fb-ce0295d8f6cf',
	// 	link: 'https://www.nike.com',
	// 	title: 'DaeChae',
	// 	team: '2인 팀프로젝트',
	// 	desc: '친구와 협업하여 친환경 제품을 추천해주는 플랫폼을 제작해보았습니다.',
	// 	front: 'React, Sass',
	// 	back: 'Firebase Functions',
	// 	deploy: 'Firebase',
	// 	github: 'https://github.com/pauljeonn/daechae',
	// },
	// {
	// 	id: 3,
	// 	img: 'https://firebasestorage.googleapis.com/v0/b/portfolio-pauljeon.appspot.com/o/portfolio-1.png?alt=media&token=cf4fe777-27b4-465d-8d25-0d35df3718b7',
	// 	link: 'https://portfolio-pauljeon.web.app',
	// 	title: 'Portfolio Website',
	// 	team: '개인 프로젝트',
	// 	desc: '개인 포트폴리오 웹사이트 용도로 React를 사용하여 제작하였습니다. 포트폴리오 목적에 부합하도록 최대한 깔끔하게 디자인하였고, Context API를 사용하여 다크 모드 기능도 구현해보았습니다.',
	// 	front: 'React, Sass',
	// 	deploy: 'Firebase',
	// 	github: 'https://github.com/pauljeonn/portfolio-pauljeon',
	// },
	{
		id: 9,
		img: 'https://firebasestorage.googleapis.com/v0/b/portfolio-pauljeon.appspot.com/o/todo-1.png?alt=media&token=7e03eb5f-edd0-41f7-bcb0-20ec3995b8c5',
		link: 'https://todolist-41d4a.web.app',
		title: 'Todo List App',
		team: '개인 프로젝트',
		desc: 'React로 제작한 할일 관리 앱입니다. React Hooks와 Context API를 사용하여 리액트에서 상태관리하는 방법을 배울 수 있었습니다. 스타일링 측면에서는 Sass와 styled-components를 둘 다 사용해보며 각 css 전처리기의 특징 및 장단점을 비교해볼 수 있었습니다.',
		tech: ['React', 'Sass', 'styled-components', 'Firebase'],
		front: 'React, Sass, styled-components',
		deploy: 'Firebase',
		github: 'https://github.com/pauljeonn/todo-app',
	},
];
