export const products = [
	{
		id: 1,
		img: 'https://firebasestorage.googleapis.com/v0/b/portfolio-pauljeon.appspot.com/o/apple.png?alt=media&token=b14cd0a8-9a3c-470b-9048-edfcf334ae58',
		link: 'https://www.apple.com',
		title: 'E-commerce App',
		team: '개인 프로젝트',
		desc: 'test',
		stack: 'React, Redux, Node.js, Express, MongoDB',
		deploy: 'Firebase',
		github: 'test',
		domain: 'abc.com',
	},
	{
		id: 2,
		img: 'https://firebasestorage.googleapis.com/v0/b/portfolio-pauljeon.appspot.com/o/nike.png?alt=media&token=13f2587a-202d-4307-b2fb-ce0295d8f6cf',
		link: 'httpS://www.nike.com',
		title: 'DaeChae',
		team: '2인 팀프로젝트',
		desc: 'test',
	},
	{
		id: 3,
		img: 'https://firebasestorage.googleapis.com/v0/b/portfolio-pauljeon.appspot.com/o/samsung.png?alt=media&token=1637878b-2532-4094-a4ac-4c08d520e541',
		link: 'https://www.samsung.com/us/',
		title: 'My Portfolio',
		desc: '◯ test',
	},
	{
		id: 4,
		img: 'https://firebasestorage.googleapis.com/v0/b/portfolio-pauljeon.appspot.com/o/samsung.png?alt=media&token=1637878b-2532-4094-a4ac-4c08d520e541',
		link: 'https://www.samsung.com/us/',
		title: 'Face Detector',
		desc: 'test',
	},
	{
		id: 5,
		img: 'https://firebasestorage.googleapis.com/v0/b/portfolio-pauljeon.appspot.com/o/samsung.png?alt=media&token=1637878b-2532-4094-a4ac-4c08d520e541',
		link: 'https://www.samsung.com/us/',
		title: 'Weather App',
		desc: '프레임워크를 사용하지않고 HTML, CSS, 자바스크립트만 사용해서 구현하였습니다.',
	},
];
